### ISSUE TITLE
一个小小的建议：后台框架使用 koa2 怎么样？

### ISSUE THREAD

**Issue by Hellowor1d** [jiayisheji/jianshu#1]
偶然在 segmentfault 看到这个项目，非常喜欢。所以跟了过来，看到项目刚刚启动不久,而且使用了 express .
所以想咨询下作者，有没有打算更换为 koa2 ，自发版以来许多公司的新项目都会优先考虑使用了。作为新教程里的主要框架，若是能迎合这一点，我觉得会吸引更多的学习者吧～
只是作为小小的建议
另外，感谢推出这么全面的教程！加油～

**Comment by jiayisheji** [comment]
@Hellowor1d  非常感谢你的建议。我打算先用express实现，我对koa2不熟悉。现在如果去了解需要花很久时间，我的想法是先用vue2做admin管理系统，ng4做前端页面，express做后台支持，等全部功能完成，会换成做admin管理系统，vue2做前端页面，至于你说的koa2就可以考虑了。

**Comment by Hellowor1d** [comment]
非常好的想法！😋特地下了手机上的codehub ，方便跟踪你的项目~向你学习，加油…！

**Comment by Hellowor1d** [comment]
doc/admin.md 开工中，第一个问题现在应该已经不是问题啦。Webstorm 2017.1 版本已经支持 Vue 文件了

**Comment by jiayisheji** [comment]
好的，我试试

**Comment by cjywoo** [comment]
想请问下，doc目录里的文档是按照什么顺序阅读的呢？另外，这个项目目前进度是多少了呀，想跟着学习所以先来咨询下。

**Comment by jiayisheji** [comment]
@cjywoo 嗯，本来是有个README.md就是文档目录，我会把他补全。最近会更新，最近工作忙。
