### ISSUE TITLE
获取具体文章的page-data有问题

### ISSUE THREAD

**Issue by cklwblove** [jiayisheji/jianshu#10]
你好！试了下代码，在获取具体文章的时候，通过**cheerio**来获取`$('[data-name=page-data]').text()`是有问题的，结果为空，改成`.html()`即可，另外，使用`JSON.parse()`的时候一定要`try,catch`来捕获下异常。

**Comment by jiayisheji** [comment]
我不知道你为什么会出现这个情况，我刚刚在另外一个环境拉了一份代码试了一下好像也没有你说的这个问题。

我的环境：
```
node v8.4.0
npm v5.3.0
windows 7 64位
```

> 使用JSON.parse()的时候一定要try,catch来捕获下异常。

这个我下次会注意，感谢提点。

**Comment by cklwblove** [comment]
你好，楼主！经过调试，是`cheeriojs`版本问题，我是直接按照`app.js`里的内容进行调试的，并没有把楼主的`package.json`拷贝过来，因此，下载的`cheeriojs`版本是最新的**1.0.0-rc.2**，而楼主用的是**0.22.0**。不是node版本问题。
版本区别，详见[](https://github.com/cheeriojs/cheerio/blob/48eae25c93702a29b8cd0d09c4a2dce2f912d1f4/History.md)
.text() 中的`ignores script and style tags (#1018) (Haleem Assal)`
