### ISSUE TITLE
Error: SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by step2414** [jiayisheji/jianshu#11]
爬取详情的时候就会报这个错误？为什么？

**Comment by step2414** [comment]
![2017-11-02 5 26 43](https://user-images.githubusercontent.com/21058348/32318725-0b42af34-bff3-11e7-8827-8c0aadf8f41e.png)

**Comment by jiayisheji** [comment]
node版本是多少

**Comment by step2414** [comment]
@jiayisheji v7.4.0

**Comment by jiayisheji** [comment]
```
"cheerio": "^0.22.0",
"superagent": "^3.5.2"
```
这是你的的依赖吗

我刚刚试了下一下，完全ok
```
node app.js
写入完成
写入完成
写入完成
写入完成
写入完成
写入完成
写入完成
写入完成
写入完成
写入完成
写入完成
写入完成
写入完成
写入完成
写入完成
写入完成
写入完成
写入完成
写入完成
写入完成
写入完成
```
我把包发你试下。

链接: https://pan.baidu.com/s/1nuCtM21 密码: j43g

你可以看下，这是我的栗子。

**Comment by step2414** [comment]
@jiayisheji 谢谢 解决了 superagent的版本为题

**Comment by jiayisheji** [comment]
ok
