### ISSUE TITLE
项目如何运行

### ISSUE THREAD

**Issue by wy8473979981** [jiayisheji/jianshu#5]
大牛，项目怎么运行呀

**Comment by jiayisheji** [comment]
@wy8473979981 
每个业务文件夹里面的都有README.md，里面安装和使用教程。
- web  [看这里](https://github.com/jiayisheji/jianshu/tree/master/web)
- service [看这里](https://github.com/jiayisheji/jianshu/tree/master/service)

admin现在还不完善，其他你可以[看这个](https://github.com/jiayisheji/jianshu/tree/master/doc)

**Comment by wy8473979981** [comment]
非常感谢！
