### ISSUE TITLE
联调问题

### ISSUE THREAD

**Issue by sucof** [jiayisheji/jianshu#6]
@jiayisheji ，大大，这些天一直在联调web端和servic端，自己出的问题还挺多，应该是通过调用webApi中的路由，然后使用大大推荐的postman查看数据是否正确，放到web中就可以了吧？但是不知道是不是我环境问题，还是步骤问题，一直都读取数据不成功，大大能给下具体这方面的步骤吗？或者相关的教程？
另外，发现github上有个类似的jianshu前端，和大大用的技术类似，可以参考下https://github.com/jeneser/jianshu

**Comment by jiayisheji** [comment]
@sucof  
不知道你具体是什么情况，可以贴一些你的代码和浏览器请求截图。postman可以查看数据，在web端基本没啥问题，不知道你的web端http请求怎么写的，我这边已经联调了，登录和用户主页都是没问题。你要同时开启服务端服务和web端服务，才能使用，因为是2个工程，前后分离开发。
