### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by Butonix** [jiayisheji/jianshu#7]
You can write detailed instructions before launching the site or record a video, I think it will come in handy not only to me, but to others!
Thank you very much for your hard work and efforts!
Yours faithfully...

**Comment by Butonix** [comment]
I do not know, it does not work!
I do everything as per the instruction in readme
cd my-app
cd web
npm install
npm install -g typescript
npm start
http://localhost:4200
get error

**Comment by jiayisheji** [comment]
1 npm install -g typescript
2 npm install -g @angular/cli@latest
3 npm start

**Comment by Butonix** [comment]
Cannot GET /
ERROR in C:/Users/user/jj/web/src/app/pages/user/user-detail.service.ts (3,31): Cannot find module '../../core/ajax'.

ERROR in C:/Users/user/jj/web/src/app/pages/user/user-detail.service.ts (3,31): Cannot find module '../../core/ajax'.

**Comment by Butonix** [comment]
Not work

**Comment by jiayisheji** [comment]
@Butonix Bug has been fixed， updata the [code](https://github.com/jiayisheji/jianshu/commit/65dd85128e7df4ca56ea841fec94116e9d1ca4ea)

**Comment by jiayisheji** [comment]
#  Introduction
This is a Nodejs Typescript Angular Vue project
## clone project
```
git clone  https://github.com/jiayisheji/jianshu.git
```
## Project Description
### web
Front show works
#### Technology stack
- angular-cli1.2
- Angular4.3 
- lodash4.10
### admin
Backstage management
#### Technology stack
- vue-cli
- axios0.15.3
- element-ui1.1.6
- vue2.1.10
- vue-router2.2.0
- vuex2.1.2
### service
Back-end server
#### Technology stack
- node8.2
- npm5
- express4.11
- jsonwebtoken7.4.1
- lodash4.17.4
- mongoose4.8.1
- redis2.7.1
- passport0.3.2
- typescript2.4
## Run Project
```
1. Run service
cd service
npm run watch-ts   // Compile ts to js
npm run dev  // Automatically restart nodejs
[Look documents](https://github.com/jiayisheji/jianshu/tree/master/service)
2. Run web
cd web
npm run start  // start Project
[Look documents](https://github.com/jiayisheji/jianshu/tree/master/web)
2. Run admin
cd admin
npm run dev  // start Project
```
@Butonix 
I am bad English, can not record video, sorry,
You can use Google translation inside the Chinese document into English
